### ISSUE TITLE
Possible Godot 4 port?

### ISSUE THREAD

**Issue by PublicVoidUpdate** [SonicMastr/godot-vita#39]
Is there a possibility of porting this to godot 4?

**Comment by c08oprkiua** [comment]
Given the specs of the Vita, that would at least be possible to run decently.

**Comment by psychicgoldfish** [comment]
I'd like this too. If performance is an issue, then it could be limited to mobile rendering mode.

**Comment by c08oprkiua** [comment]
Well, I can say this. Someone was working on porting Godot 4 to the 3DS and got decently far, and that console is much weaker than the Vita. Therefore, it should be perfectly doable for the Vita.

**Comment by technicaljicama** [comment]
> I'd like this too. If performance is an issue, then it could be limited to mobile rendering mode.

Nope, you'd have to create a new renderer from scratch, the vita only supports up to GLES2.

**Comment by c08oprkiua** [comment]
From what I've looked at, the graphics for a platform in Godot 4 are handled in a very modular, somewhat A.N.G.L.E. reminiscent way. Making a graphics backend for the Vita that works in GLES2 calls with that should be doable...?

**Comment by technicaljicama** [comment]
Maybe it would be easier to backport the gles2 renderer from Godot 3

**Comment by c08oprkiua** [comment]
To an extent, the code could probably be reused/slightly tweaked to work, yeah. But there *would* still be some amount of original code that would have to be written, because Godot 4's graphics system is very different, at least at a glance. I haven't worked with the code of Godot 3 and under much, but from a quick glance over the servers, Godot 3 has one Visual Server, whereas Godot 4 has a Rendering Server and Display Server(s). RenderingDevice based classes are likely what most of the Godot 3 visual server code would translate to in Godot 4 (based on glancing over the file names), and a custom Display Server would have to be implemented as well for more general graphics calls.
